export const ORDER = {
  CREATE_REQUEST: "CREATE_REQUEST",
  CREATE_SUCCESS: "CREATE_SUCCESS",
  CREATE_FAIL: "CREATE_FAIL",

  DETAILS_REQUEST: "DETAILS_REQUEST",
  DETAILS_SUCCESS: "DETAILS_SUCCESS",
  DETAILS_FAIL: "DETAILS_FAIL",
  DETAILS_RESET: "DETAILS_RESET",

  LIST_MY_REQUEST: "LIST_MY_REQUEST",
  LIST_MY_SUCCESS: "LIST_MY_SUCCESS",
  LIST_MY_FAIL: "LIST_MY_FAIL",
  LIST_MY_RESET: "LIST_MY_RESET",

  PAY_REQUEST: "PAY_REQUEST",
  PAY_SUCCESS: "PAY_SUCCESS",
  PAY_FAIL: "PAY_FAIL",
  PAY_RESET: "PAY_RESET",
};
