export const USER = {
  USER_LOGIN_REQUEST: "USER_LOGIN_REQUEST",
  USER_LOGIN_SUCCESS: "USER_LOGIN_SUCCESS",
  USER_LOGIN_FAIL: "USER_LOGIN_FAIL",
  USER_LOGOUT: "USER_LOGOUT",

  REGISTER_REQUEST: "USER_REGISTER_REQUEST",
  REGISTER_SUCCESS: "USER_REGISTER_SUCCESS",
  REGISTER_FAIL: "USER_REGISTER_FAIL",

  LIST_REQUEST: "USER_LIST_REQUEST",
  LIST_SUCCESS: "USER_LIST_SUCCESS",
  LIST_FAIL: "USER_LIST_FAIL",
  LIST_RESET: "USER_LIST_RESET",

  DELETE_REQUEST: "USER_DELETE_REQUEST",
  DELETE_SUCCESS: "USER_DELETE_SUCCESS",
  DELETE_FAIL: "USER_DELETE_FAIL",
  DELETE_RESET: "USER_DELETE_RESET",

  UPDATE_REQUEST: "USER_UPDATE_REQUEST",
  UPDATE_SUCCESS: "USER_UPDATE_SUCCESS",
  UPDATE_FAIL: "USER_UPDATE_FAIL",
  UPDATE_RESET: "USER_UPDATE_RESET",

  DETAILS_REQUEST: "USER_DETAILS_REQUEST",
  DETAILS_SUCCESS: "USER_DETAILS_SUCCESS",
  DETAILS_FAIL: "USER_DETAILS_FAIL",
  DETAILS_RESET: "USER_DETAILS_RESET",

  UPDATE_PROFILE_REQUEST: "USER_UPDATE_PROFILE_REQUEST",
  UPDATE_PROFILE_SUCCESS: "USER_UPDATE_PROFILE_SUCCESS",
  UPDATE_PROFILE_FAIL: "USER_UPDATE_PROFILE_FAIL",
  UPDATE_PROFILE_RESET: "USER_UPDATE_PROFILE_RESET",
};
