export const USER = {
  USER_LOGIN_REQUEST: "USER_LOGIN_REQUEST",
  USER_LOGIN_SUCCESS: "USER_LOGIN_SUCCESS",
  USER_LOGIN_FAIL: "USER_LOGIN_FAIL",
  USER_LOGOUT: "USER_LOGOUT",
  REGISTER_REQUEST: "USER_REGISTER_REQUEST",
  REGISTER_SUCCESS: "USER_REGISTER_SUCCESS",
  REGISTER_FAIL: "USER_REGISTER_FAIL",

  DETAILS_REQUEST: "USER_DETAILS_REQUEST",
  DETAILS_SUCCESS: "USER_DETAILS_SUCCESS",
  DETAILS_FAIL: "USER_DETAILS_FAIL",
  DETAILS_RESET: "USER_DETAILS_RESET",

  UPDATE_PROFILE_REQUEST: "USER_UPDATE_PROFILE_REQUEST",
  UPDATE_PROFILE_SUCCESS: "USER_UPDATE_PROFILE_SUCCESS",
  UPDATE_PROFILE_FAIL: "USER_UPDATE_PROFILE_FAIL",
  UPDATE_PROFILE_RESET: "USER_UPDATE_PROFILE_RESET",
};
